/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgranhotel.vistas;

import com.toedter.calendar.JDateChooser;
import elgranhotel.modelo.Conexion;
import elgranhotel.modelo.Habitacion;
import elgranhotel.modelo.HabitacionData;
import elgranhotel.modelo.Huesped;
import elgranhotel.modelo.HuespedData;
import elgranhotel.modelo.Reservas;
import elgranhotel.modelo.ReservasData;
import elgranhotel.modelo.TipoHabitacion;
import elgranhotel.modelo.TipoHabitacionData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHIDORY
 */
public class VistaReservas extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private List<Huesped> listaHuesped;
    private List<Reservas> listaReservas;
    private HuespedData huesData;
    private HabitacionData habitacionData;
    private TipoHabitacionData thabitacionData;
    private ReservasData resData;
    private int cantidadp;
    
    private Conexion conexion;
     
     

    /**
     * Creates new form vistaReservas
     */
    public VistaReservas() {
        
        try {
            initComponents();
            
            conexion = new Conexion("jdbc:mysql://localhost/ElGranHotel", "root", "");
            
            modelo = new DefaultTableModel();
            
            huesData = new HuespedData(conexion);
            listaHuesped = huesData.obtenerHuesped();
                                  
            habitacionData = new HabitacionData(conexion);
            
            
            thabitacionData = new TipoHabitacionData(conexion);
           
            
            resData = new ReservasData(conexion);
            
            
            
            
            armaCabeceraTabla();
            
            
            borraFilasTabla();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         
    }
    
   
    
    public void armaCabeceraTabla() {

        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID Habitacion");
        columnas.add("Estado");
        columnas.add("ID T. Habitacion");
        columnas.add("Tipo    ");
        columnas.add("Codigo");
        columnas.add("Cant. Personas");
        columnas.add("Cant. Camas");
        columnas.add("Tipo Camas");
        columnas.add("Precio Noche");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        ttabla.setModel(modelo);
        
        
    }
    
    public void borraFilasTabla(){
    
    int a =modelo.getRowCount()-1;
    System.out.println("Tabla "+a);
    for(int i=a;i>=0;i--){
    modelo.removeRow(i );
    System.out.println("Tabla "+i);
    
   
    }
    
    
    
    
    }
      //Cuenta cantidad de dias entre dos fechas
    public void difDias(JDateChooser ent, JDateChooser ffin){
        
         if (ent.getDate() != null && ffin.getDate() != null ) {
             Calendar fE = ent.getCalendar();
             Calendar fS = ffin.getCalendar();
             int dias = 0;
             while(fE.before(fS) || fE.equals(fS)){
                 dias++;
                 fE.add(Calendar.DATE, 1);
             }
                tfCantDias.setText(String.valueOf(dias));
            
         }
        
                
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfDomicilio = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dcSalida = new com.toedter.calendar.JDateChooser();
        lFentrada = new javax.swing.JLabel();
        dcEntrada = new com.toedter.calendar.JDateChooser();
        tfMontoEstadia = new javax.swing.JTextField();
        lCantidadDias = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCantDias = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCantPersonas = new javax.swing.JTextField();
        lCantidadDias1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bCrearReserva1 = new javax.swing.JButton();
        rbActiva = new javax.swing.JRadioButton();
        rbInactiva = new javax.swing.JRadioButton();
        bBuscarx = new javax.swing.JButton();
        rbOcupada = new javax.swing.JRadioButton();
        rbLibre = new javax.swing.JRadioButton();
        rbHuesped = new javax.swing.JRadioButton();
        rbReservasInactivas = new javax.swing.JRadioButton();
        bFinReserva = new javax.swing.JButton();
        rbReservasActivas = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Crear Reservas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 700, 50));

        b3.setBackground(new java.awt.Color(102, 0, 51));
        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(102, 0, 51));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel4.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 570, -1));

        b2.setBackground(new java.awt.Color(102, 0, 51));
        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 0, 51));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel4.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 630, -1));

        b1.setBackground(new java.awt.Color(102, 0, 51));
        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(102, 0, 51));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel4.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 700, -1));

        ttabla.setBackground(new java.awt.Color(0, 102, 153));
        ttabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ttabla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttabla.setForeground(new java.awt.Color(102, 0, 51));
        ttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5"
            }
        ));
        ttabla.setGridColor(new java.awt.Color(102, 0, 51));
        ttabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttabla);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1340, 270));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Nombre");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Correo");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Celular");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("____  >");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 51));
        jLabel11.setText("____  >");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 51));
        jLabel12.setText("____  >");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 150, -1));

        tfNombre.setBackground(new java.awt.Color(0, 102, 153));
        tfNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 330, 30));

        tfDomicilio.setBackground(new java.awt.Color(0, 102, 153));
        tfDomicilio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        tfDomicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDomicilio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 330, 30));

        tfCorreo.setBackground(new java.awt.Color(0, 102, 153));
        tfCorreo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCorreo.setForeground(new java.awt.Color(255, 255, 255));
        tfCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 330, 30));

        tfCelular.setBackground(new java.awt.Color(0, 102, 153));
        tfCelular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCelular.setForeground(new java.awt.Color(255, 255, 255));
        tfCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCelular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 330, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 51));
        jLabel17.setText("____  >");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        tfDni.setBackground(new java.awt.Color(0, 102, 153));
        tfDni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfDni.setForeground(new java.awt.Color(255, 255, 255));
        tfDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 330, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 51));
        jLabel18.setText("____  >");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Domicilio");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Dni");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        dcSalida.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evet) {
                difDias( dcEntrada, dcSalida);

            }
        });
        dcSalida.setBackground(new java.awt.Color(102, 0, 51));
        dcSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        dcSalida.setFocusable(false);
        dcSalida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(dcSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 150, -1));

        lFentrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lFentrada.setForeground(new java.awt.Color(255, 255, 255));
        lFentrada.setText("Fecha Entrada");
        lFentrada.setToolTipText("");
        jPanel4.add(lFentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        dcEntrada.setBackground(new java.awt.Color(102, 0, 51));
        dcEntrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        dcEntrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(dcEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, -1));

        tfMontoEstadia.setBackground(new java.awt.Color(0, 102, 153));
        tfMontoEstadia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfMontoEstadia.setForeground(new java.awt.Color(102, 0, 51));
        tfMontoEstadia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMontoEstadia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfMontoEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMontoEstadiaActionPerformed(evt);
            }
        });
        jPanel4.add(tfMontoEstadia, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 150, 40));

        lCantidadDias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lCantidadDias.setForeground(new java.awt.Color(255, 255, 255));
        lCantidadDias.setText("Monto Estadia");
        lCantidadDias.setToolTipText("");
        jPanel4.add(lCantidadDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cant Personas ");
        jLabel2.setToolTipText("");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, -1));

        tfCantDias.setBackground(new java.awt.Color(0, 102, 153));
        tfCantDias.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfCantDias.setForeground(new java.awt.Color(102, 0, 51));
        tfCantDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCantDias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(tfCantDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Salida");
        jLabel8.setToolTipText("");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        tfCantPersonas.setBackground(new java.awt.Color(0, 102, 153));
        tfCantPersonas.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        tfCantPersonas.setForeground(new java.awt.Color(102, 0, 51));
        tfCantPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCantPersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfCantPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantPersonasActionPerformed(evt);
            }
        });
        jPanel4.add(tfCantPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 120, 70));

        lCantidadDias1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lCantidadDias1.setForeground(new java.awt.Color(255, 255, 255));
        lCantidadDias1.setText("Cantidad Dias");
        lCantidadDias1.setToolTipText("");
        jPanel4.add(lCantidadDias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 51));
        jLabel13.setText("____  >");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 51));
        jLabel14.setText("____  >");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 51));
        jLabel15.setText("____  >");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 51));
        jLabel16.setText("____  >");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 150, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 51));
        jLabel20.setText("____  >");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 150, -1));

        b4.setBackground(new java.awt.Color(102, 0, 51));
        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(102, 0, 51));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel4.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 630, -1));

        b5.setBackground(new java.awt.Color(102, 0, 51));
        b5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b5.setForeground(new java.awt.Color(102, 0, 51));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel4.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 510, -1));

        b6.setBackground(new java.awt.Color(102, 0, 51));
        b6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b6.setForeground(new java.awt.Color(102, 0, 51));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel4.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 570, -1));

        bCrearReserva1.setBackground(new java.awt.Color(102, 0, 51));
        bCrearReserva1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCrearReserva1.setForeground(new java.awt.Color(255, 255, 255));
        bCrearReserva1.setText("Crear Reserva");
        bCrearReserva1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCrearReserva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearReserva1ActionPerformed(evt);
            }
        });
        jPanel4.add(bCrearReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 310, 30));

        rbActiva.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup2.add(rbActiva);
        rbActiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbActiva.setForeground(new java.awt.Color(102, 0, 51));
        rbActiva.setText("Activa");
        rbActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivaActionPerformed(evt);
            }
        });
        jPanel4.add(rbActiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, -1, -1));

        rbInactiva.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup2.add(rbInactiva);
        rbInactiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbInactiva.setForeground(new java.awt.Color(102, 0, 51));
        rbInactiva.setText("Inactiva");
        rbInactiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInactivaActionPerformed(evt);
            }
        });
        jPanel4.add(rbInactiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 400, -1, -1));

        bBuscarx.setBackground(new java.awt.Color(102, 0, 51));
        bBuscarx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBuscarx.setForeground(new java.awt.Color(255, 255, 255));
        bBuscarx.setText("Busqueda ");
        bBuscarx.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBuscarx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarxActionPerformed(evt);
            }
        });
        jPanel4.add(bBuscarx, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 390, 30));

        rbOcupada.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbOcupada);
        rbOcupada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbOcupada.setForeground(new java.awt.Color(102, 0, 51));
        rbOcupada.setText("Hab. Ocupada");
        rbOcupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOcupadaActionPerformed(evt);
            }
        });
        jPanel4.add(rbOcupada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, -1, -1));

        rbLibre.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbLibre);
        rbLibre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbLibre.setForeground(new java.awt.Color(102, 0, 51));
        rbLibre.setText("Hab. Libre");
        rbLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLibreActionPerformed(evt);
            }
        });
        jPanel4.add(rbLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 90, -1));

        rbHuesped.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbHuesped);
        rbHuesped.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbHuesped.setForeground(new java.awt.Color(102, 0, 51));
        rbHuesped.setText("Huesped Estado Reserva");
        rbHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHuespedActionPerformed(evt);
            }
        });
        jPanel4.add(rbHuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 200, -1, 20));

        rbReservasInactivas.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbReservasInactivas);
        rbReservasInactivas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbReservasInactivas.setForeground(new java.awt.Color(102, 0, 51));
        rbReservasInactivas.setText("Reservas Inactiva");
        rbReservasInactivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReservasInactivasActionPerformed(evt);
            }
        });
        jPanel4.add(rbReservasInactivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 280, -1, 20));

        bFinReserva.setBackground(new java.awt.Color(102, 0, 51));
        bFinReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bFinReserva.setForeground(new java.awt.Color(255, 255, 255));
        bFinReserva.setText("Fin Reserva");
        bFinReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bFinReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinReservaActionPerformed(evt);
            }
        });
        jPanel4.add(bFinReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 450, 30));

        rbReservasActivas.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbReservasActivas);
        rbReservasActivas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbReservasActivas.setForeground(new java.awt.Color(102, 0, 51));
        rbReservasActivas.setText("Reservas Activa");
        rbReservasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReservasActivasActionPerformed(evt);
            }
        });
        jPanel4.add(rbReservasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, -1, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

    }//GEN-LAST:event_b1ActionPerformed

    private void ttablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttablaMouseClicked
        if(tfCantDias.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccionar una fecha de entrada y salida");

        }else if (rbLibre.isSelected()) {
            int filaSeleccionada = ttabla.getSelectedRow();
            System.out.println("Fila seleccionada " + filaSeleccionada);

            if (filaSeleccionada != -1) {

                double precioNoche = (double) modelo.getValueAt(filaSeleccionada, 8);

                int cantidad = Integer.parseInt(tfCantDias.getText());
                Habitacion thab = new Habitacion();
                thab.calcularMonto(precioNoche, cantidad);
                tfMontoEstadia.setText(String.valueOf(thab.getMonto()));

            }
        } else {
            System.out.println("La condicion no es para esta tabla");
        }
    }//GEN-LAST:event_ttablaMouseClicked

    private void tfMontoEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMontoEstadiaActionPerformed

    }//GEN-LAST:event_tfMontoEstadiaActionPerformed

    private void tfCantPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantPersonasActionPerformed

    }//GEN-LAST:event_tfCantPersonasActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void bCrearReserva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearReserva1ActionPerformed

        if (tfCantPersonas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad de personas para buscar una Habitacion");

        } else if (tfMontoEstadia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione una Habitacion de la Tabla");

        } else if (tfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Nombre");

        } else if (tfDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Dni");

        } else if (tfDomicilio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Domicilio");

        } else if (tfCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Celular");

        }else if((rbActiva.isSelected() == false && rbInactiva.isSelected() == false) ){
            JOptionPane.showMessageDialog(null, "Selecione Activa o Inactiva para crear la Reserva");
        }else{

            String nombre = tfNombre.getText();
            int dni = Integer.parseInt(tfDni.getText());
            String domicilio = tfDomicilio.getText();
            String correo = tfCorreo.getText();
            long celular = Long.parseLong(tfCelular.getText());
            int cantidad = Integer.parseInt(tfCantDias.getText());
            LocalDate fE = dcEntrada.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fS = dcSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            double importe = Double.parseDouble(tfMontoEstadia.getText());
            boolean activa = rbActiva.isSelected();

            int filaSeleccionada = ttabla.getSelectedRow();
            System.out.println("Fila seleccionada " + filaSeleccionada);
            if (filaSeleccionada != -1) {

                int idhab = (int) modelo.getValueAt(filaSeleccionada, 0);

                int idthab = (int) modelo.getValueAt(filaSeleccionada, 2);

                //aqui se crea la reserva
                Huesped huesped = new Huesped(nombre, dni, domicilio, correo, celular);
                huesData.guardarHuesped(huesped);
                Huesped hues = huesData.buscarHuesped(huesped.getId_huesped());

                TipoHabitacion thab = thabitacionData.buscarThabitacion(idthab);
                Habitacion hab = habitacionData.buscarHabitacion(idhab);
                hab.setThabitacion(thab);

                Reservas reserva = new Reservas(hues, hab, cantidad, fE, fS, importe, activa);
                resData.guardarReservas(reserva);
                habitacionData.actualizarEstadoHabitacion(idhab, idthab, true);

                JOptionPane.showMessageDialog(null, "La Reserva Nº "+reserva.getId()+" donde aloja el Huesped llamado: "+huesped.getNombre()+" se Guardo Exitosamente!!!");

            }
            tfNombre.setText("");
            tfDni.setText("");
            tfDomicilio.setText("");
            tfCorreo.setText("");
            tfCelular.setText("");
            tfMontoEstadia.setText("");

        }

    }//GEN-LAST:event_bCrearReserva1ActionPerformed

    private void rbActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivaActionPerformed
        rbOcupada.setSelected(false);
    }//GEN-LAST:event_rbActivaActionPerformed

    private void rbInactivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInactivaActionPerformed
        rbOcupada.setSelected(false);
    }//GEN-LAST:event_rbInactivaActionPerformed

    private void bBuscarxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarxActionPerformed
        if(tfCantPersonas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad de personas para buscar una Habitacion");

        }else if (rbOcupada.isSelected() || rbLibre.isSelected()) {

            borraFilasTabla();
            boolean libre = rbLibre.isSelected();
            HabitacionData hab = new HabitacionData(conexion);
            cantidadp = Integer.parseInt(tfCantPersonas.getText());

            for (Habitacion tha : hab.obtenerHabiporTipo(cantidadp, !libre)) {
                modelo.addRow(new Object[]{tha.getId_habitacion(), tha.getEstado(), tha.getThabitacion().getId_thabitacion(),
                    tha.getThabitacion().getTipo(), tha.getThabitacion().getCodigo(), tha.getThabitacion().getCantPersonas(),
                    tha.getThabitacion().getCantCamas(), tha.getThabitacion().getTipoCamas(), tha.getThabitacion().getPrecioNoche()});
        }

        }else if (rbHuesped.isSelected()) {
            borraFilasTabla();
            listaHuesped = huesData.obtenerHuespedAcordeEstadoReserva();

            for (Huesped hues : listaHuesped) {
                modelo.addRow(new Object[]{hues.getId_huesped(), hues.getNombre(), hues.getDni(),
                    hues.getDomicilio(), hues.getCorreo(),hues.getCelular()
                });

            }
        } else if (rbReservasActivas.isSelected()) {
            borraFilasTabla();
            listaReservas = resData.obtenerReservas(true);

            for (Reservas res : listaReservas) {
                modelo.addRow(new Object[]{res.getId(), res.getHuesped().getId_huesped()+" - "+ res.getHuesped().getNombre(),"Piso - "+ res.getHabitaciones().getId_habitacion(), res.getCantDias(),
                    res.getFechaEntrada(), res.getFechaSalida(),res.getImporteTotal(), res.getEstado()
                });

            }

        }else if(rbReservasInactivas.isSelected()){
             borraFilasTabla();
            listaReservas = resData.obtenerReservas(false);

            for (Reservas res : listaReservas) {
                modelo.addRow(new Object[]{res.getId(), res.getHuesped().getId_huesped()+" - "+ res.getHuesped().getNombre(), "Piso - "+res.getHabitaciones().getId_habitacion(), res.getCantDias(),
                    res.getFechaEntrada(), res.getFechaSalida(),res.getImporteTotal(), res.getEstado()
                });

            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una opcion de busqueda");
        }
    }//GEN-LAST:event_bBuscarxActionPerformed

    private void rbOcupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOcupadaActionPerformed
        modelo.setColumnCount(0);
        rbOcupada.setSelected(false);
        armaCabeceraTabla();
    }//GEN-LAST:event_rbOcupadaActionPerformed

    private void rbLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLibreActionPerformed
        modelo.setColumnCount(0);
        rbLibre.setSelected(false);
        armaCabeceraTabla();

    }//GEN-LAST:event_rbLibreActionPerformed

    private void rbHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHuespedActionPerformed
        modelo.setColumnCount(0);

        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID ");
        columnas.add("Nombre ");
        columnas.add("DNI ");
        columnas.add("Domicilio ");
        columnas.add("Correo ");
        columnas.add("Celular");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        ttabla.setModel(modelo);
    }//GEN-LAST:event_rbHuespedActionPerformed

    private void rbReservasInactivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReservasInactivasActionPerformed
        modelo.setColumnCount(0);

        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID ");
        columnas.add("ID Huesped ");
        columnas.add("ID Habitacion ");
        columnas.add("Cant. Dias ");
        columnas.add("Fecha Entrada ");
        columnas.add("Fecha Salida");
        columnas.add("Importe Total");
        columnas.add("Estado");
        
       

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        ttabla.setModel(modelo);
       
    }//GEN-LAST:event_rbReservasInactivasActionPerformed

    private void bFinReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinReservaActionPerformed
        if (rbHuesped.isSelected()) {
            int filaSeleccionada = ttabla.getSelectedRow();
            System.out.println("Fila seleccionada " + filaSeleccionada);
            
            if (filaSeleccionada != -1) {
                int idhues = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
               
                
                Huesped hues = new Huesped();
                hues.setId(idhues);
                
                resData.finReserava(hues,false);
                
                JOptionPane.showMessageDialog(null, "La reserva se paso a Inactiva y la Habitacion se paso a Libre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione la opcion Huesped y una celda de la tabla para dar fin a la reserva");
        }
    }//GEN-LAST:event_bFinReservaActionPerformed

    private void rbReservasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReservasActivasActionPerformed
        modelo.setColumnCount(0);

        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID ");
        columnas.add("ID Huesped ");
        columnas.add("ID Habitacion ");
        columnas.add("Cant. Dias ");
        columnas.add("Fecha Entrada ");
        columnas.add("Fecha Salida");
        columnas.add("Importe Total");
        columnas.add("Estado");
        
       

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        ttabla.setModel(modelo);
    }//GEN-LAST:event_rbReservasActivasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton bBuscarx;
    private javax.swing.JButton bCrearReserva1;
    private javax.swing.JButton bFinReserva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dcEntrada;
    private com.toedter.calendar.JDateChooser dcSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCantidadDias;
    private javax.swing.JLabel lCantidadDias1;
    private javax.swing.JLabel lFentrada;
    private javax.swing.JRadioButton rbActiva;
    private javax.swing.JRadioButton rbHuesped;
    private javax.swing.JRadioButton rbInactiva;
    private javax.swing.JRadioButton rbLibre;
    private javax.swing.JRadioButton rbOcupada;
    private javax.swing.JRadioButton rbReservasActivas;
    private javax.swing.JRadioButton rbReservasInactivas;
    private javax.swing.JTextField tfCantDias;
    private javax.swing.JTextField tfCantPersonas;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfMontoEstadia;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTable ttabla;
    // End of variables declaration//GEN-END:variables
}
