/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgranhotel.vistas;

import javax.swing.JFrame;

/**
 *
 * @author CHIDORY
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal1
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mReservas = new javax.swing.JMenu();
        miCrearReserva = new javax.swing.JMenuItem();
        mHabitaciones = new javax.swing.JMenu();
        miBuscarHabitacion = new javax.swing.JMenuItem();
        mThabitacion = new javax.swing.JMenu();
        miCrearHabitaciones = new javax.swing.JMenuItem();
        mHuesped = new javax.swing.JMenu();
        miBuscarHuesped = new javax.swing.JMenuItem();
        mInforme = new javax.swing.JMenu();
        miInformeDni = new javax.swing.JMenuItem();
        mSa = new javax.swing.JMenu();
        miSalirAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        jMenuBar1.setForeground(new java.awt.Color(101, 97, 97));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mReservas.setText("Reservas");
        mReservas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReservasActionPerformed(evt);
            }
        });

        miCrearReserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miCrearReserva.setText("Crear Reserva");
        miCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearReservaActionPerformed(evt);
            }
        });
        mReservas.add(miCrearReserva);

        jMenuBar1.add(mReservas);

        mHabitaciones.setText("Habitaciones");
        mHabitaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        miBuscarHabitacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miBuscarHabitacion.setText("Buscar Habitacion");
        mHabitaciones.add(miBuscarHabitacion);

        jMenuBar1.add(mHabitaciones);

        mThabitacion.setText("T.Habitaciones");
        mThabitacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        miCrearHabitaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miCrearHabitaciones.setText("Crear Habitaciones ");
        mThabitacion.add(miCrearHabitaciones);

        jMenuBar1.add(mThabitacion);

        mHuesped.setText("Huesped");
        mHuesped.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        miBuscarHuesped.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miBuscarHuesped.setText("Buscar Huesped");
        mHuesped.add(miBuscarHuesped);

        jMenuBar1.add(mHuesped);

        mInforme.setText("Informe");
        mInforme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        miInformeDni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miInformeDni.setText("Crear Informe por DNI");
        miInformeDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInformeDniActionPerformed(evt);
            }
        });
        mInforme.add(miInformeDni);

        jMenuBar1.add(mInforme);

        mSa.setText("Salir");
        mSa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        miSalirAplicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        miSalirAplicacion.setText("Salir de Aplicacion");
        miSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirAplicacionActionPerformed(evt);
            }
        });
        mSa.add(miSalirAplicacion);

        jMenuBar1.add(mSa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miInformeDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInformeDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miInformeDniActionPerformed

    private void miSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirAplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSalirAplicacionActionPerformed

    private void miCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearReservaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
          VistaReservas res = new VistaReservas();
          res.setVisible(true);
        escritorio.add(res);
        escritorio.moveToFront(res);
    }//GEN-LAST:event_miCrearReservaActionPerformed

    private void mReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mHabitaciones;
    private javax.swing.JMenu mHuesped;
    private javax.swing.JMenu mInforme;
    private javax.swing.JMenu mReservas;
    private javax.swing.JMenu mSa;
    private javax.swing.JMenu mThabitacion;
    private javax.swing.JMenuItem miBuscarHabitacion;
    private javax.swing.JMenuItem miBuscarHuesped;
    private javax.swing.JMenuItem miCrearHabitaciones;
    private javax.swing.JMenuItem miCrearReserva;
    private javax.swing.JMenuItem miInformeDni;
    private javax.swing.JMenuItem miSalirAplicacion;
    // End of variables declaration//GEN-END:variables
}
