/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgranhotel.vistas;

import elgranhotel.modelo.Conexion;
import elgranhotel.modelo.Habitacion;
import elgranhotel.modelo.HabitacionData;
import elgranhotel.modelo.TipoHabitacion;
import elgranhotel.modelo.TipoHabitacionData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alejandrox33
 */
public class VistaCrearHabitaciones extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private TipoHabitacionData thabD;
    private HabitacionData habD;
    private List<Habitacion> listaHabitaciones;
    private Conexion conexion;
    private Habitacion hab;
    private TipoHabitacion thab;
    private boolean estado;
    private int simple;
    private int doble;
    private int triple;
    private int suitL;
    

    /**
     * Creates new form VistaCrearHabitaciones
     */
    public VistaCrearHabitaciones() {
        try {
            initComponents();
            conexion = new Conexion("jdbc:mysql://localHost/ElGranHotel", "root", "");

            modelo = new DefaultTableModel();
            
            thabD = new TipoHabitacionData(conexion);
          
            habD = new HabitacionData(conexion);
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al conectar con la base de datos..." + ex.getMessage());
        }

    }
    
    public void cabeceraTabla(){
        
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID Habitacion");
        columnas.add("Estado");
        columnas.add("ID T. Habitacion");
        columnas.add("Tipo ");
        columnas.add("Codigo");
        columnas.add("Cant. Personas");
        columnas.add("Cant. Camas");
        columnas.add("Tipo Camas");
        columnas.add("Precio Noche");
        
        for (Object co : columnas) {
            
            modelo.addColumn(co);
        }
        ttabla.setModel(modelo);
        
        
    }
    
    public void borrarFilasTablas(){
        int numeroFilas = modelo.getRowCount()-1;
        System.out.println("Tabla "+numeroFilas);
        
        for (int i = numeroFilas; i >= 0; i--) {
            modelo.removeRow(i);
            System.out.println("Tabla "+i);
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfDesde = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfCantPersonas = new javax.swing.JTextField();
        tfTipoCamas = new javax.swing.JTextField();
        tfCantCamas = new javax.swing.JTextField();
        rbOcupadas = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bCrearHabitacion = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bBuscar2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        tfPrecioNoche = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfHasta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rbLibre = new javax.swing.JRadioButton();
        lSl = new javax.swing.JLabel();
        lD = new javax.swing.JLabel();
        lS = new javax.swing.JLabel();
        lT = new javax.swing.JLabel();
        lSL = new javax.swing.JLabel();
        lSimple = new javax.swing.JLabel();
        lDoble = new javax.swing.JLabel();
        lTriple = new javax.swing.JLabel();
        lTipoH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(" Crear Habitaciones          ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 640, 50));

        ttabla.setBackground(new java.awt.Color(0, 102, 153));
        ttabla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ttabla.setForeground(new java.awt.Color(102, 0, 51));
        ttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ttabla.setGridColor(new java.awt.Color(255, 255, 255));
        ttabla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ttabla.setSelectionForeground(new java.awt.Color(102, 0, 51));
        jScrollPane1.setViewportView(ttabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1240, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("____  >");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Nº Hab. Desde");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Codigo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Cant. Personas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("____  >");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 51));
        jLabel11.setText("____  >");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 51));
        jLabel12.setText("____  >");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 51));
        jLabel13.setText("____  >");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 51));
        jLabel14.setText("____  >");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Cant. Camas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 110, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Tipo Camas");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Precio Noche");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        tfDesde.setBackground(new java.awt.Color(0, 102, 153));
        tfDesde.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfDesde.setForeground(new java.awt.Color(255, 255, 255));
        tfDesde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDesde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 270, 30));

        tfTipo.setBackground(new java.awt.Color(0, 102, 153));
        tfTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTipo.setForeground(new java.awt.Color(255, 255, 255));
        tfTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 270, 30));

        tfCodigo.setBackground(new java.awt.Color(0, 102, 153));
        tfCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 270, 30));

        tfCantPersonas.setBackground(new java.awt.Color(0, 102, 153));
        tfCantPersonas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCantPersonas.setForeground(new java.awt.Color(255, 255, 255));
        tfCantPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCantPersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfCantPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 30));

        tfTipoCamas.setBackground(new java.awt.Color(0, 102, 153));
        tfTipoCamas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTipoCamas.setForeground(new java.awt.Color(255, 255, 255));
        tfTipoCamas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTipoCamas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfTipoCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 270, 30));

        tfCantCamas.setBackground(new java.awt.Color(0, 102, 153));
        tfCantCamas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCantCamas.setForeground(new java.awt.Color(255, 255, 255));
        tfCantCamas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCantCamas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfCantCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 270, 30));

        rbOcupadas.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbOcupadas);
        rbOcupadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbOcupadas.setForeground(new java.awt.Color(102, 0, 51));
        rbOcupadas.setText("Habitacion ocupada");
        rbOcupadas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbOcupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOcupadasActionPerformed(evt);
            }
        });
        jPanel2.add(rbOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, -1, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 570, 1230, 30));

        b3.setBackground(new java.awt.Color(102, 0, 51));
        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(102, 0, 51));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel2.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 530, -1));

        bBorrar.setBackground(new java.awt.Color(102, 0, 51));
        bBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBorrar.setForeground(new java.awt.Color(255, 255, 255));
        bBorrar.setText("Borrar");
        bBorrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(bBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 310, 30));

        bCrearHabitacion.setBackground(new java.awt.Color(102, 0, 51));
        bCrearHabitacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCrearHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        bCrearHabitacion.setText("Crear Habitacion");
        bCrearHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCrearHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearHabitacionActionPerformed(evt);
            }
        });
        jPanel2.add(bCrearHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 420, 30));

        bActualizar.setBackground(new java.awt.Color(102, 0, 51));
        bActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bActualizar.setText("Actualizar");
        bActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 360, 30));

        bBuscar2.setBackground(new java.awt.Color(102, 0, 51));
        bBuscar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        bBuscar2.setText("Buscar");
        bBuscar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar2ActionPerformed(evt);
            }
        });
        jPanel2.add(bBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 480, 30));

        b2.setBackground(new java.awt.Color(102, 0, 51));
        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 0, 51));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 580, -1));

        b1.setBackground(new java.awt.Color(102, 0, 51));
        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(102, 0, 51));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 640, -1));

        tfPrecioNoche.setBackground(new java.awt.Color(0, 102, 153));
        tfPrecioNoche.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfPrecioNoche.setForeground(new java.awt.Color(255, 255, 255));
        tfPrecioNoche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPrecioNoche.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfPrecioNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 270, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 51));
        jLabel17.setText("____  >");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        tfHasta.setBackground(new java.awt.Color(0, 102, 153));
        tfHasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfHasta.setForeground(new java.awt.Color(255, 255, 255));
        tfHasta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHasta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(tfHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 270, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 51));
        jLabel18.setText("____  >");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Tipo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Nº Hab. Hasta");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        rbLibre.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(rbLibre);
        rbLibre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbLibre.setForeground(new java.awt.Color(102, 0, 51));
        rbLibre.setText("Habitacion libre");
        rbLibre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLibreActionPerformed(evt);
            }
        });
        jPanel2.add(rbLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, -1, -1));

        lSl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lSl.setForeground(new java.awt.Color(255, 255, 255));
        lSl.setText("Suit De Lujo:");
        jPanel2.add(lSl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 90, -1));

        lD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lD.setForeground(new java.awt.Color(255, 255, 255));
        lD.setText("Estandar Doble :");
        jPanel2.add(lD, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 110, -1));

        lS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lS.setForeground(new java.awt.Color(255, 255, 255));
        lS.setText("Estandar Simple :");
        jPanel2.add(lS, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 120, -1));

        lT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lT.setForeground(new java.awt.Color(255, 255, 255));
        lT.setText("Estandar Triple:");
        jPanel2.add(lT, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 110, -1));

        lSL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSL.setForeground(new java.awt.Color(102, 0, 51));
        lSL.setText("0");
        jPanel2.add(lSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));

        lSimple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSimple.setForeground(new java.awt.Color(102, 0, 51));
        lSimple.setText("0");
        jPanel2.add(lSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        lDoble.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lDoble.setForeground(new java.awt.Color(102, 0, 51));
        lDoble.setText("0");
        jPanel2.add(lDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, -1, -1));

        lTriple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lTriple.setForeground(new java.awt.Color(102, 0, 51));
        lTriple.setText("0");
        jPanel2.add(lTriple, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        lTipoH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTipoH.setForeground(new java.awt.Color(240, 240, 240));
        lTipoH.setText("Opcion de Tipo de Habitacion: Estándar Simple, Doble, Triple, o Suite Lujo ");
        jPanel2.add(lTipoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Opcion de Tipo de Camas: Simples, Queen, King Size");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1237, 609));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
    }//GEN-LAST:event_b3ActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        int filaSeleccionada = ttabla.getSelectedRow();
        System.out.println("Fila seleccionada "+filaSeleccionada);
        
        if (filaSeleccionada != -1) {
            int idhab = Integer.parseInt(modelo.getValueAt(filaSeleccionada,0).toString()) ;
            boolean estado = Boolean.parseBoolean(modelo.getValueAt(filaSeleccionada,1).toString());
            int idthab = Integer.parseInt(modelo.getValueAt(filaSeleccionada,2).toString());
            String tipo =(String)modelo.getValueAt(filaSeleccionada,3);
            int codigo = Integer.parseInt(modelo.getValueAt(filaSeleccionada,4).toString());
            int cantPersonas =Integer.parseInt(modelo.getValueAt(filaSeleccionada,5).toString());
            int cantCamas = Integer.parseInt(modelo.getValueAt(filaSeleccionada,6).toString()) ;
            String tipoCamas =(String)modelo.getValueAt(filaSeleccionada,7);
            double precioNoche = Double.parseDouble(modelo.getValueAt(filaSeleccionada,8).toString());
            
            Habitacion h = habD.buscarHabitacion(idhab);
            habD.borrarHabitacion(idhab);
            thabD.borrarThabitacion(idthab);
            
            JOptionPane.showMessageDialog(null, "La Habitacion " +h.getId_habitacion() + " se borro con Exito...");
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una celda de la tabla para Borrar");
            
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bCrearHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearHabitacionActionPerformed
        if (tfDesde.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero de Habitacion Desde");

        } else if (tfHasta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero de Habitacion Hasta");

        } else if (tfTipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Tipo");

        } else if (tfCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Codigo");

        } else if (tfCantPersonas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Cantidad de Personas");

        } else if (tfTipoCamas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Tipo de Camas");

        } else if (tfCantCamas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Cantidad de Camas");

        } else if (tfPrecioNoche.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Precio por Noche");

        } else {
            int desde = Integer.parseInt(tfDesde.getText());
            int hasta = Integer.parseInt(tfHasta.getText());
            String tipo = tfTipo.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            int cantP = Integer.parseInt(tfCantPersonas.getText());
            String tipoC = tfTipoCamas.getText();
            int cantC = Integer.parseInt(tfCantCamas.getText());
            double precioN = Double.parseDouble(tfPrecioNoche.getText());

            habD.crearHabitacionPorTipo(desde, hasta, tipo, codigo, cantP, cantC, tipoC, precioN, false);

            JOptionPane.showMessageDialog(null, "Las Habitaciones se crearon con Exito");

            tfDesde.setText("");
            tfHasta.setText("");
            tfTipo.setText("");
            tfCodigo.setText("");
            tfCantPersonas.setText("");
            tfTipoCamas.setText("");
            tfCantCamas.setText("");
            tfPrecioNoche.setText("");
        }


    }//GEN-LAST:event_bCrearHabitacionActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        int filaSeleccionada = ttabla.getSelectedRow();
        System.out.println("Fila seleccionada "+filaSeleccionada);
        
        if (filaSeleccionada != -1 ) {
            int idhab = Integer.parseInt(modelo.getValueAt(filaSeleccionada,0).toString()) ;
            boolean estado = Boolean.parseBoolean(modelo.getValueAt(filaSeleccionada,1).toString());
            int idthab = Integer.parseInt(modelo.getValueAt(filaSeleccionada,2).toString());
            String tipo =(String)modelo.getValueAt(filaSeleccionada,3);
            int codigo = Integer.parseInt(modelo.getValueAt(filaSeleccionada,4).toString());
            int cantPersonas =Integer.parseInt(modelo.getValueAt(filaSeleccionada,5).toString());
            int cantCamas = Integer.parseInt(modelo.getValueAt(filaSeleccionada,6).toString()) ;
            String tipoCamas =(String)modelo.getValueAt(filaSeleccionada,7);
            double precioNoche = Double.parseDouble(modelo.getValueAt(filaSeleccionada,8).toString());
            
            thab = new TipoHabitacion(idthab, tipo, codigo, cantPersonas, cantCamas, tipoCamas, precioNoche);
            thabD.actualizarThabitacion(thab);
            TipoHabitacion id = thabD.buscarThabitacion(thab.getId_thabitacion());
            
            
            hab = new Habitacion(idhab, id, estado);
            habD.actualizarHabitacion(hab);
         
                       
            JOptionPane.showMessageDialog(null, "La Habitacion Nº "+hab.getId_habitacion()+" se Actualizo con Exito");
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una celda de la tabla para Actualizar");
            
        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar2ActionPerformed
        if(rbLibre.isSelected() == false && rbOcupadas.isSelected() == false){
          JOptionPane.showMessageDialog(null, "Seleccione una opcion de busqueda");
          
        }else if (rbLibre.isSelected() || rbOcupadas.isSelected()) {
           
            borrarFilasTablas();
            estado = rbLibre.isSelected();
            listaHabitaciones = habD.obtenerHabiporTipo(!estado);
            
            for (Habitacion hab : listaHabitaciones) {
                modelo.addRow(new Object[]{hab.getId_habitacion(), hab.getEstado(), hab.getThabitacion().getId_thabitacion(),
                    hab.getThabitacion().getTipo(), hab.getThabitacion().getCodigo(), hab.getThabitacion().getCantPersonas(),
                    hab.getThabitacion().getCantCamas(), hab.getThabitacion().getTipoCamas(), hab.getThabitacion().getPrecioNoche()});
            }
            
            simple = habD.contadorHabitacionPorTipo("Simple");
            doble = habD.contadorHabitacionPorTipo("Doble");
            triple = habD.contadorHabitacionPorTipo("Triple");
            suitL = habD.contadorHabitacionPorTipo("Suit Lujo");

            lSimple.setText(String.valueOf(simple));
            lDoble.setText(String.valueOf(doble));
            lTriple.setText(String.valueOf(triple));
            lSL.setText(String.valueOf(suitL));
        }
        
    }//GEN-LAST:event_bBuscar2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
    }//GEN-LAST:event_b1ActionPerformed

    private void rbLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLibreActionPerformed
        modelo.setColumnCount(0);
        cabeceraTabla();
    }//GEN-LAST:event_rbLibreActionPerformed

    private void rbOcupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOcupadasActionPerformed
        modelo.setColumnCount(0);
        cabeceraTabla();
    }//GEN-LAST:event_rbOcupadasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBuscar2;
    private javax.swing.JButton bCrearHabitacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lD;
    private javax.swing.JLabel lDoble;
    private javax.swing.JLabel lS;
    private javax.swing.JLabel lSL;
    private javax.swing.JLabel lSimple;
    private javax.swing.JLabel lSl;
    private javax.swing.JLabel lT;
    private javax.swing.JLabel lTipoH;
    private javax.swing.JLabel lTriple;
    private javax.swing.JRadioButton rbLibre;
    private javax.swing.JRadioButton rbOcupadas;
    private javax.swing.JTextField tfCantCamas;
    private javax.swing.JTextField tfCantPersonas;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDesde;
    private javax.swing.JTextField tfHasta;
    private javax.swing.JTextField tfPrecioNoche;
    private javax.swing.JTextField tfTipo;
    private javax.swing.JTextField tfTipoCamas;
    private javax.swing.JTable ttabla;
    // End of variables declaration//GEN-END:variables
}
